name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
env:
  CI: true
jobs:
  setup:
    if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
    name: Setup
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      CHROMIUM_BIN: ${{ steps.env.outputs.CHROMIUM_BIN }}
      test-ui: ${{ steps.filter.outputs.test-ui }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            test-ui:
              - 'src/**'
              - 'package-lock.json'
              - 'tsconfig.*'
              - 'playwright*.config.ts'
              - 'vite.config.ts'
              - '.github/workflows/ci.yml'
      - name: Export env variables
        id: env
        if: ${{ steps.filter.outputs.test-ui == 'true' }}
        run: |
          echo "CHROMIUM_BIN=$(which chromium-browser)" >> $GITHUB_OUTPUT

  test-playwright:
    name: Test with Playwright
    needs: setup
    if: ${{ needs.setup.outputs.test-ui == 'true' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      CHROMIUM_BIN: ${{ needs.setup.outputs.CHROMIUM_BIN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npm run test:playwright
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  test-vitest-browser:
    name: Test with Vitest browser mode
    needs: setup
    if: ${{ needs.setup.outputs.test-ui == 'true' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      CHROMIUM_BIN: ${{ needs.setup.outputs.CHROMIUM_BIN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run Vitest
        run: npm run test:vitest

  build:
    name: Build
    needs: test-vitest-browser
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
