name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  changes:
    name: Detect changes
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      runtime: ${{ steps.filter.outputs.runtime }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            runtime:
              - 'src/**'
              - 'package-lock.json'
              - '!**/*.md'
              - '!**/playwright/**'
              - '!**/.github/**'

  test:
    needs: changes
    if: ${{ needs.changes.outputs.runtime == 'true' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install chromium
      - name: Get changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            runtime:
              - 'src/**'
              - '!**/*.md'
              - '!**/playwright/**'
      - name: Run Playwright tests
        if: ${{ steps.filter.outputs.runtime == 'true' }}
        run: npm run test:playwright
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
