name: UI Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
env:
  CI: true
jobs:
  changes:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    name: Detect changes
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      test-ui: ${{ steps.filter.outputs.test-ui }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get changed files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            test-ui:
              - 'src/**'
              - 'package-lock.json'
              - 'tsconfig.*'
              - 'playwright*.config.ts'
              - 'vite.config.ts'
              - '.github/workflows/testing.yml'

  test-playwright:
    name: Test with Playwright
    needs: changes
    if: ${{ needs.changes.outputs.test-ui == 'true' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Set path to Chromium binary
        run: echo "CHROMIUM_BIN=$(which chromium-browser)" >> $GITHUB_ENV
      - name: Run Playwright tests
        run: npm run test:playwright
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  test-vitest-browser:
    name: Test with Vitest browser mode
    needs: changes
    if: ${{ needs.changes.outputs.test-ui == 'true' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Set path to Chromium binary
        run: echo "CHROMIUM_BIN=$(which chromium-browser)" >> $GITHUB_ENV
      - name: Run Vitest
        run: npm run test:vitest
